<?php

namespace UserBundle\Repository;

/**
 * AgendeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendeRepository extends \Doctrine\ORM\EntityRepository
{
}
