<?php

namespace UserBundle\Repository;

/**
 * cittaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cittaRepository extends \Doctrine\ORM\EntityRepository
{
}
