<?php

namespace UserBundle\Repository;

/**
 * MaterieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterieRepository extends \Doctrine\ORM\EntityRepository
{
}
