<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
            public function getLivelloScol()
             {
            return $livello = $this ->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT u.livelloScolastico FROM UserBundle:User u')
            ->getResult();
             }


             public function getRicerca($city,$livello,$matery)
             {
               if($livello==null){
                return $this->getEntityManager()
                ->createQuery(
                'SELECT u, Materie
                 FROM UserBundle:User u
                 JOIN u.idCitta citta
                 JOIN u.materie Materie
                 WHERE citta.nome = :city AND Materie.nome = :matery')
                ->setParameter('city',$city)
                ->setParameter('matery',$matery)
                ->getResult();
               }
               else{
                return $this->getEntityManager()
                ->createQuery(
                'SELECT u, Materie
                 FROM UserBundle:User u
                 JOIN u.idCitta citta
                 JOIN u.materie Materie
                 WHERE citta.nome = :city AND Materie.nome = :matery AND u.livelloScolastico = :livello')
                ->setParameter('city',$city)
                ->setParameter('matery',$matery)
                ->setParameter('livello',$livello)
                ->getResult();
               }

             }


}


