user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

about:
    path:     /chi-siamo
    defaults: { _controller: UserBundle:Default:about }

docenti:
    path:     /docenti
    defaults: { _controller: UserBundle:Default:docente }



