user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

about:
    path:     /chi-siamo
    defaults: { _controller: UserBundle:Default:about }

docenti:
    path:     /docenti
    defaults: { _controller: UserBundle:Default:docente }


docente:
    path:     /docente/{id}
    defaults: { _controller: UserBundle:Default:doce }


agende:
    path:     /agende/{id}
    defaults: { _controller: UserBundle:Default:editAgende }


edit:
    path:     /edit/{id}
    defaults: { _controller: UserBundle:Default:editProfilo}


